name: commit-to-main
on:
 push:
   branches:
   - main
 pull_request:
   branches:
   - main
   
env:
  TEST_PROJECT_PATH: 'Tests.EfCore.Filtering/Tests.EfCore.Filtering.csproj'
  CONFIGURATION: 'Debug'

jobs:
 build_test:
  name: 'Testing Commit'
  runs-on: 'windows-latest'  
  steps:
  - name: 'Checkout'
    uses: actions/checkout@v2

  - name: 'Setup dot 6'
    uses: 'actions/setup-dotnet@v1'
    with:
     dotnet-version: 6.x

  - name: 'Restore packages'
    run: dotnet restore ${{ env.TEST_PROJECT_PATH }}
        
  - name: Build Solution
    run: dotnet build ${{ env.TEST_PROJECT_PATH }} --no-restore --configuration ${{ env.CONFIGURATION }}

  - name: Tests
    run: dotnet test ${{ env.TEST_PROJECT_PATH }} --no-build --no-restore