name: nuget-build-and-deploy
on:
 release:
  types: [published]
    
env:
  SOLUTION_NAME: 'EFCore.Filtering.sln'
  PROJECT_PATH: 'EfCore.Filtering.Mvc/EfCore.Filtering.Mvc.csproj'
  TEST_PROJECT_PATH: 'Tests.EfCore.Filtering/Tests.EfCore.Filtering.csproj'
  CONFIGURATION: 'Release'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v3/index.json'

jobs:
 build_test_deploy:
  name: 'Deploy To Nuget'
  runs-on: 'windows-latest'  
  environment: 'Deployment'
  steps:

  - name: 'Checkout'
    uses: actions/checkout@v2

  - name: 'Setup dot net 5 and 6'
    uses: 'actions/setup-dotnet@v1'
    with:
     dotnet-version: |
      5.x
      6.x
      
  - name: 'Restore packages'
    run: dotnet restore ${{ env.SOLUTION_NAME }}
        
  - name: Build Solution
    run: dotnet build ${{ env.SOLUTION_NAME }} --no-restore --configuration ${{ env.CONFIGURATION }}

  - name: Tests
    run: dotnet test ${{ env.TEST_PROJECT_PATH }} --no-build --no-restore

  - name: 'Get version'
    id: get_version
    uses: battila7/get-version-action@v2
   
  - name: 'Pack project'
    run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --configuration ${{ env.CONFIGURATION }} -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

  - name: 'Publish package'
    run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg --source ${{ env.NUGET_SOURCE_URL }} --api-key ${{ secrets.NUGET_AUTH_TOKEN }} 