name: nuget-build-and-deploy
on:
 push:
  branches: 
    - main
  tags:
    - v*
    
env:
  PROJECT_PATH: 'EfCore.Filtering.Mvc/EfCore.Filtering.Mvc.csproj'
  CONFIGURATION: 'Release'
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}\output
  NUGET_SOURCE_URL: 'https://api.nuget.org/v1/index.json'

jobs:
 build_test_deploy:
  name: 'Build'
  runs-on: 'windows-latest'  
  steps:
  - name: 'Checkout'
    uses: actions/checkout@v2

  - name: 'Setup dot net 5 and 6'
    uses: 'actions/setup-dotnet@v1'
    with:
     dotnet-version: |
      5.x
      6.x
      
  - name: 'Restore packages'
    run: dotnet restore $PROJECT_PATH

  - name: '$CONFIGURATION Build $PROJECT_PATH'
    run: dotnet build $PROJECT_PATH --no-restore --configuration $CONFIGURATION 

  - name: Test
    run: dotnet test Tests.EfCore.Filtering --no-build --no-restore

  - name: 'Get version'
    id: version
    uses: battila7/get-version-action@v2

  - name: 'Pack project $PROJECT_PATH'
    run: dotnet pack $PROJECT_PATH --no-build --no-restore --configuration $CONFIGURATION -p:PackageVersion=${{ steps.version.output.version-without-v }} --output $PACKAGE_OUTPUT_DIRECTORY

  #- name: 'Push package'
  #  run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}\*.nupkg -k ${{ secrets.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}